using UnrealBuildTool;

public class OakGame : ModuleRules {
    public OakGame(ReadOnlyTargetRules Target) : base(Target) {
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
        
        PublicDependencyModuleNames.AddRange(new string[] {
            "AIModule",
            "AnimGraphRuntime",
            "AnimationCore",
            "ApexDestruction",
            "CinematicCamera",
            "Core",
            "CoreUObject",
            "Engine",
            "EngineSettings",
            "GameplayTags",
            "GameplayTasks",
            "GbxAI",
            "GbxAbilities",
            "GbxAnimRuntime",
            "GbxAnimRuntimeBase",
            "GbxAudio",
            "GbxCameraModes",
            "GbxDestruction",
            "GbxDialog",
            "GbxDynamicRoom",
            "GbxFluidSimulation",
            "GbxGameSystemCore",
            "GbxInput",
            "GbxInventory",
            "GbxLevelSequence",
            "GbxMission",
            "GbxNav",
            "GbxRuntime",
            "GbxSpawn",
            "GbxStreamingInteraction",
            "GbxTimeOfDay",
            "GbxTravelStation",
            "GbxUI",
            "GbxVehicle",
            "GbxWeapon",
            "ImmediatePhysics",
            "InputCore",
            "LevelSequence",
            "MediaAssets",
            "MovieScene",
            "NavigationSystem",
            "OnlineSubsystem",
            "OnlineSubsystemUtils",
            "Overlay",
            "PhysXVehicles",
            "ProceduralMeshComponent",
            "ReplicationGraph",
            "ScaleformUI",
            "SignificanceManager",
            "SlateCore",
            "UMG",
            "WwiseAudio",
        });
    }
}
