#include "GbxNavMeshPainterComponent.h"

void UGbxNavMeshPainterComponent::SetPainterEnabled(bool bNewEnabled) {
}

void UGbxNavMeshPainterComponent::SetPainterAlwaysEnabled(bool bNewAlwaysEnabled) {
}

void UGbxNavMeshPainterComponent::ResetToStatic() {
}

bool UGbxNavMeshPainterComponent::IsPainterEnabled() const {
    return false;
}

UGbxNavMeshPainterComponent::UGbxNavMeshPainterComponent() {
    this->bAlwaysEnabled = false;
    this->bEnabled = true;
    this->IdleTime = 0.25f;
    this->PainterType = EGbxPainterType::StaticAndDynamic;
    this->GbxNavArea = NULL;
    this->PainterId = 4294967295;
    this->PainterMovedThreshold = 25.00f;
    this->bBlocksAutoGeneratedUserEdges = false;
    this->NavArea = NULL;
}

