#pragma once
#include "CoreMinimal.h"
#include "ETechnicalBones.generated.h"

UENUM(BlueprintType)
enum class ETechnicalBones : uint8 {
    Body,
    LeftMuffler,
    RightMuffler,
    Engine,
    R_Axle,
    R_R_Wheel,
    R_L_Wheel,
    F_R_Wheel,
    F_L_Wheel,
    F_L_Axle,
    F_L_Steering,
    F_L_Steering_T,
    F_L_SteeringShaft,
    F_L_SuspensionUp,
    F_L_SuspensionBodyUp_T,
    F_L_SuspensionBodyDn,
    F_L_SuspensionDn_T,
    F_L_SuspensionSprings,
    F_L_SuspensionSpringsBody,
    F_R_Axle,
    F_R_Steering,
    F_R_Steering_T,
    F_R_SteeringShaft,
    F_R_SuspensionUp,
    F_R_SuspensionBodyUp_T,
    F_R_SuspensionBodyDn,
    F_R_SuspensionDn_T,
    F_R_SuspensionSprings,
    F_R_SuspensionSpringsBody,
    F_Cannon,
    F_Cannon_Visual,
    Turret,
    Player2,
    R_DriveShaftPole,
    R_DriveShaftBodyPole,
    R_DriveShaftAttach,
    R_DriveShaftBodyAttach,
    F_R_DriveShaft00,
    F_R_DriveShaft01,
    F_R_DriveShaft02,
    F_L_DriveShaft00,
    F_L_DriveShaft01,
    F_L_DriveShaft02,
    SteeringWheel,
    F_R_Wheel_Hover,
    F_L_Wheel_Hover,
    R_R_Wheel_Hover,
    R_L_Wheel_Hover,
    F_DriveShaftAttach,
    F_DriveShaftPole,
    F_DriveShaftBodyAttach,
    R_L_Suspension_Body,
    R_L_Suspension_Axle,
    R_R_Suspension_Body,
    R_R_Suspension_Axle,
    EngineShaft,
    EngineBelt,
    Seat,
    Count,
};

